source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/myiOSComponent/myRepo.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'TKDataStorage_Example' do
  pod 'TKDataStorage', :path => '../'

  target 'TKDataStorage_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
    pod 'TKModelMapping', '~> 0.0.12'
  end
end
